use_small_heuristics = "Max"
empty_item_single_line = false
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
