[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.54"
clang = { version = "1.0.3", features = ["clang_10_0"] }
clap = { version = "3.0.14", features = ["derive"] }
either = "1.6.1"
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.14"
nom = "7.1.0"
