[package]
name = "scanner"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.54"
clang = { version = "2.0.0", features = ["clang_10_0"] }
clap = { version = "4.5.0", features = ["derive"] }
either = "1.6.1"
env_logger = "0.11.0"
itertools = "0.13.0"
log = "0.4.14"
nom = "7.1.0"
