version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
    rust: "latest"
  apt_packages:
    - libclang1
    - libclang-dev
    - meson
    - libev-dev
    - libdbus-1-dev
    - libxcb-randr0-dev
    - libxcb-xinput-dev
    - libxcb-xkb-dev
    - libxcb-keysyms1-dev
    - libxkbcommon-dev
    - liblua5.3-dev
    - libudev-dev
sphinx:
  configuration: docs/conf.py
